apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-app
    run: multi-container
spec:
  containers:
    - name: girus-nginx-1
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          memory: "64Mi"
          cpu: "0.3"
    - name: girus-alpine-2
      image: alpine
      resources:
        limits:
          cpu: "0.5"
          memory: "128Mi"
        requests:
          memory: "64Mi"
          cpu: "0.3"
      args:
        - sleep
        - "1800"