apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-stress
spec:
  containers:
  - name: ubuntu-stress
    image: ubuntu
    args: 
      - sleep
      - infinity
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "250m"
