apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-server
  name: nginx-server
spec:
  containers:
  - image: nginx
    name: nginx-server
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
